<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Support\Locales;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

/**
 * Flattens `lang/{locale}/*.php` into one JSON bundle per locale plus a TypeScript
 * union of every valid key.
 *
 * Why a build artifact rather than an Inertia prop: a 21-module ERP runs to roughly a
 * thousand strings, and shipping that as a shared prop would re-send it on every
 * visit. As a static asset Vite code-splits it into one browser-cached chunk per
 * locale, and Inertia shares only the locale string.
 *
 * The key union is what turns `t('console.overvie.heading')` into a tsc error instead
 * of a blank space on the page — which matters more here than usual, because there is
 * no test suite to catch it.
 *
 * Output is committed, so a fresh clone type-checks. `bun run check:i18n` re-runs this
 * and fails if anything differs, so the artifacts cannot drift from the PHP.
 */
final class ExportLangCommand extends Command
{
    protected $signature = 'lang:export {--output= : Write to this directory instead of the project (used by check:i18n to compare without touching the tree)}';

    protected $description = 'Export lang/ into JSON bundles and a TypeScript key union for the client';

    private const BUNDLE_DIR = 'resources/js/lang';

    private const TYPES_FILE = 'resources/js/types/lang.d.ts';

    public function handle(): int
    {
        $bundles = [];
        $out = $this->stringOption('output');

        foreach (Locales::codes() as $locale) {
            $bundles[$locale] = $this->flattenLocale($locale);
        }

        File::ensureDirectoryExists($this->target(self::BUNDLE_DIR, $out));
        File::ensureDirectoryExists(dirname($this->target(self::TYPES_FILE, $out)));

        foreach ($bundles as $locale => $messages) {
            $this->put(
                self::BUNDLE_DIR."/{$locale}.json",
                json_encode($messages, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)."\n",
                $out,
            );
        }

        $this->put(self::TYPES_FILE, $this->keyUnion(array_keys($bundles[Locales::BASE])), $out);

        if ($out !== null) {
            return self::SUCCESS;
        }

        $this->components->info(sprintf(
            'Exported %d keys × %d locales.',
            count($bundles[Locales::BASE]),
            count($bundles),
        ));

        return self::SUCCESS;
    }

    /**
     * Every string in one locale, keyed `file.dot.path`.
     *
     * @return array<string, string>
     */
    private function flattenLocale(string $locale): array
    {
        $messages = [];

        foreach (glob(base_path("lang/{$locale}/*.php")) ?: [] as $file) {
            $namespace = basename($file, '.php');

            /** @var array<string, mixed> $contents */
            $contents = require $file;

            $messages = [...$messages, ...$this->flatten($contents, $namespace)];
        }

        ksort($messages);

        return $messages;
    }

    /**
     * @param  array<string, mixed>  $messages
     * @return array<string, string>
     */
    private function flatten(array $messages, string $prefix): array
    {
        $flat = [];

        foreach ($messages as $key => $value) {
            $path = "{$prefix}.{$key}";

            if (is_array($value)) {
                $flat = [...$flat, ...$this->flatten($value, $path)];

                continue;
            }

            $flat[$path] = (string) $value;
        }

        return $flat;
    }

    /** @param  list<string>  $keys */
    private function keyUnion(array $keys): string
    {
        $union = implode("\n", array_map(
            static fn (string $key): string => "    | '{$key}'",
            $keys,
        ));

        return <<<TS
            // Generated by `php artisan lang:export` — do not edit.
            // Every key in the base locale ({$this->baseLocale()}). A `t()` call for anything
            // else is a type error, which is how a typo surfaces without a test suite.

            export type TranslationKey =
            {$union};

            TS."\n";
    }

    private function baseLocale(): string
    {
        return Locales::BASE;
    }

    private function put(string $relative, string $contents, ?string $out): void
    {
        File::put($this->target($relative, $out), $contents);

        if ($out === null) {
            $this->line("  <fg=gray>wrote</> {$relative}");
        }
    }

    /** Where a generated file goes: the project, or an --output directory mirroring it. */
    private function target(string $relative, ?string $out): string
    {
        return $out === null ? base_path($relative) : rtrim($out, '/').'/'.$relative;
    }

    private function stringOption(string $name): ?string
    {
        $value = $this->option($name);

        return is_string($value) && $value !== '' ? $value : null;
    }
}
