import type { Messages } from '@/lib/i18n';

/**
 * Loads a locale's message bundle, code-split so a browser downloads only the
 * language it is being served.
 *
 * The bundles are generated by `php artisan lang:export` from `lang/`, which stays
 * the single source of truth.
 *
 * On the module-level cache: this holds *bundles keyed by locale*, which is not the
 * "global mutable locale state" that would make concurrent SSR unsafe. Nothing here
 * records which locale is current — that only ever comes from the page props of the
 * render asking for it. Entries are immutable once loaded, so two SSR renders in
 * different languages read different keys of the same map and cannot interfere.
 */

const bundles = import.meta.glob<{ default: Messages }>('../lang/*.json');

const loaded = new Map<string, Messages>();

const FALLBACK = 'en';

/**
 * Await this before rendering a page in `locale` — it is called from Inertia's
 * `resolve`, which runs on the server and again on every client navigation, so by the
 * time anything renders the bundle is already in hand.
 */
export async function loadMessages(locale: string): Promise<Messages> {
    const cached = loaded.get(locale);

    if (cached) {
        return cached;
    }

    const loader =
        bundles[`../lang/${locale}.json`] ??
        bundles[`../lang/${FALLBACK}.json`];

    // A locale with no bundle at all would be a build problem, not a runtime one; an
    // empty map degrades to showing keys rather than crashing the page.
    if (!loader) {
        return {};
    }

    const messages = (await loader()).default;
    loaded.set(locale, messages);

    return messages;
}

/**
 * The already-loaded bundle, synchronously. Safe during render precisely because
 * `loadMessages` has been awaited in `resolve` first.
 */
export function messagesFor(locale: string): Messages {
    return loaded.get(locale) ?? loaded.get(FALLBACK) ?? {};
}
